---
# Exploratory Data Analysis
DataVis Supplementary Material

---
Exploratory data analysis is primarily used to investigate data sets before making any assumptions beforehand. Since human beings are visual creatures, data exploration often means using data visualization methods to better understand patterns within the data, detect anomalies and find relations among the variables. With that knowledge, existing questions could be refined, and new ones could be generated. The most common steps in exploratory data analysis are: **importing**, **cleaning**, **processing** and **visualizing** the data.

In [1]:
import numpy as np
import pandas as pd
import altair as alt
from sklearn import datasets
from sklearn.metrics import mutual_info_score as mis
from sklearn.preprocessing import StandardScaler

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/3713260676.py", line 2, in <module>
    import pandas as pd
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/3713260676.py", line 2, in <module>
    import pandas as pd
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

In [2]:
# Uncomment if you are using dark jupyter lab/notebook theme
#alt.renderers.set_embed_options(theme='dark')

---
## Data import

For the purposes of introducing you to exploratory data analysis, we will import 3 different data sets, among which two of them have categorical and one has continuous *target* variables.
Through this notebook, we will only deal with one data set, named *data_wine*, which is a classic multi-class dataset. You should repeat exploratory analysis with two other data sets. Since we are using the *pandas* library to handle data sets, we will use *data frame* and *data set* interchangeably.

In [3]:
data_iris = datasets.load_iris (as_frame = True).frame
data_diabetes = datasets.load_diabetes (as_frame = True).frame
data_wine = datasets.load_wine (as_frame = True).frame

First, we will inspect first five rows (entries) of the data set.

In [4]:
data_wine.tail(10)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
168,13.58,2.58,2.69,24.5,105.0,1.55,0.84,0.39,1.54,8.660000,0.74,1.80,750.0,2
169,13.40,4.60,2.86,25.0,112.0,1.98,0.96,0.27,1.11,8.500000,0.67,1.92,630.0,2
170,12.20,3.03,2.32,19.0,96.0,1.25,0.49,0.40,0.73,5.500000,0.66,1.83,510.0,2
171,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,2
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.700000,0.62,1.71,660.0,2
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.700000,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.300000,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.200000,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.300000,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.200000,0.61,1.60,560.0,2

Then, we will inspect the summary of the data set.

In [5]:
data_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

Last, we will inspect the descriptive statistics of the data set in order to get a feeling of the underlying data.

In [6]:
data_wine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

---
## Correlation matrix chart

As you might already know, a correlation matrix is a table showing correlation coefficients between variables. Determining the correlation is one of the most important parts of the data examination for machine learning purposes. Data having non-correlated features have many benefits, such as: learning will be faster, there won't be much bias, etc. Also, if we have too highly correlated features, we could easily remove one of them from the data set without losing vital information.

In [7]:
def create_corr_chart (data):
    
    # Removing target column
    new_data = data.drop ('target', axis = 1)
    
    # We are using Pearson correlation.
    # We need reset_index and melt to transform data set from wide to long format
    # For more info: https://altair-viz.github.io/user_guide/data.html#data-long-vs-wide
    corr = new_data.corr(method = 'pearson').reset_index().melt('index')
    corr.columns = ['var_1', 'var_2', 'correlation']
    
    # Create correlation matrix chart
    chart = alt.Chart(corr).mark_rect().encode(
        alt.X ('var_1', title = None, axis = alt.Axis(labelAngle = -45)),
        alt.Y ('var_2', title = None),
        alt.Color('correlation', legend = None, scale = alt.Scale(scheme = 'redblue', reverse = True)),
    ).properties(
        width = alt.Step(40),
        height = alt.Step(40)
    )
    
    # Create text values for each colored element on top of existing chart
    chart += chart.mark_text(size = 12).encode(
        alt.Text ('correlation', format = ".2f"),
        color = alt.condition("abs(datum.correlation) > 0.5", alt.value('white'), alt.value('black'))
    )
    
    # If we want to return the chart with upper triangle as well, we should remove .transform...
    return chart.transform_filter("datum.var_1 < datum.var_2")

In [8]:
chart_corr_wine = create_corr_chart (data_wine)
chart_corr_wine

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tk/qh_5gfz51996p7zxwjyl8r140000gp/T/ipykernel_7629/554312483.py", line 2, in <module>
    chart_corr_wine
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 268, in __call__
    format_dict, md_dict = self.compute_format_data(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/displayhook.py", line 157, in compute_format_data
    return self.shell.display_formatter.format(result)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 152, in format
    format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 226, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/IPython/core/formatters.py", line 977, in __call__
    return method(include=include, exclude=exclude)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2571, in _repr_mimebundle_
    dct = self.to_dict(context={"pre_transform": False})
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in _todict
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 474, in <listcomp>
    return [_todict(v, context) for v in obj]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 960, in to_dict
    result = _todict(
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 476, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/schemapi.py", line 472, in _todict
    return obj.to_dict(validate=False, context=context)
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/vegalite/v5/schema/channels.py", line 54, in to_dict
    parsed = parse_shorthand(shorthand, data=context.get("data", None))
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/core.py", line 592, in parse_shorthand
    if pyarrow_available() and data is not None and isinstance(data, DataFrameLike):
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 94, in pyarrow_available
    import_pyarrow_interchange()
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/altair/utils/_importers.py", line 77, in import_pyarrow_interchange
    import pyarrow.interchange as pi
  File "/Users/DubeyA-Dev/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

alt.LayerChart(...)

### Exercise:
(**EASY**) Show only upper triangle of the chart above.

### Exercise:
(**MEDIUM**) Calculate the (pairwise) mutual information matrix for each feature (dataframe column) and plot it. Use built-in functions of the *sklearn* library.

---
## Parallel coordinates chart

Visualizing data sets with 2 or 3 dimensions is relatively easy, and could be done in multiple ways. Relations between variables could be visualized with scatter plots, bar charts, pie charts, etc. On the other hand, if we have datasets with more than 4 dimensions, visualizing relationships becomes challenging with conventional charts. However, parallel coordinates chart can include many dimensions, so that each axis represents one variable of the data set. The biggest strength of this charts is that the variables can have values with different ranges and even with different units.

In [9]:
def create_parallel_chart (data):
    
    new_data = data.reset_index().melt(id_vars = ['index', 'target'])
    
    chart = alt.Chart(new_data).mark_line().encode(
        alt.X ('variable:N'),
        alt.Y ('value:Q'),
        alt.Color ('target:N'),
        alt.Detail ('index:N'),
        opacity = alt.value(0.4),
    ).properties(width = 1000)
    
    return chart

In [10]:
# We have to omit 'proline' and 'magnesium' columns because they skew up the resulting chart. Try without removing
chart_parallel_wine = create_parallel_chart (data_wine.drop (['proline', 'magnesium'], axis = 1))
chart_parallel_wine

alt.Chart(...)

Scaling can sometimes play a crucial step in finding out patterns that were hidden before applying this data transformation. Scaling transforms the raw data to a new scale that is common with the scales of other variables.

In [11]:
# Let's see what happens if we scale data
scaler_wine = StandardScaler()
scaled_data_wine = scaler_wine.fit_transform (data_wine.drop ('target', axis = 1))
scaled_data_wine = pd.DataFrame(scaled_data_wine, columns = data_wine.drop ('target', axis = 1).columns)
scaled_data_wine['target'] = data_wine['target']
scaled_data_wine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,1.518613,-0.562250,0.232053,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009,0
1,0.246290,-0.499413,-0.827996,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242,0
2,0.196879,0.021231,1.109334,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148,0
3,1.691550,-0.346811,0.487926,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574,0
4,0.295700,0.227694,1.840403,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874,0

In [12]:
chart_parallel_scaled_wine = create_parallel_chart (scaled_data_wine.drop (['proline', 'magnesium'], axis = 1))
chart_parallel_scaled_wine

alt.Chart(...)

With parallel coordinates charts, axis ordering is quite important, as it can reveal data structures that are not easily seen when axes are ordered in a certain way. Optimizing the order of the vertical axis can decrease the clutter of the parallel plot i.e. minimize the number of intersections between lines.

### Exercise:
(**EASY**) Try out different axis ordering, plot chart, and see if it gives better visual structure or not.

### Exercise:
(**EASY**) Instead of standardizing data, normalize it. Then plot that data with parallel coordinates chart.

### Exercise:
(**MEDIUM**) Implement filtering, so that when we hover the mouse over the blue line (class 0), all lines other than blue ones are grayed out.

### Exercise:
(**HARD**) Plot minimum, maximum and medium values for each and every variable on parallel coordinates chart. Help and examples can be found here:
* https://github.com/altair-viz/altair/issues/1034
* https://stackoverflow.com/questions/54671453/parallel-coordinates-in-vega-lite/54701776#54701776
* https://vega.github.io/vega/examples/parallel-coordinates/

---
## Scatter plot matrix

A scatter plot is an efficient way to visualize 2D or 3D data (Cartesian plane + color). When we want to quickly visualize all pairwise relationships of the multivariate data set, we can use a scatter plot for each relationship and create a matrix of those plots. With this type of chart we can answer some important questions about the data set we have: what features are correlated, is there multicollinearity, is the data linearly separable...

In [13]:
def create_scatter_matrix (data):
    
    # We want to remove 'target' from our list of features
    features = data.columns.values[data.columns.values != 'target']
    
    chart = alt.Chart(data).mark_circle().encode(
        alt.X(alt.repeat("column"), type = 'quantitative', scale = alt.Scale (nice = True)),
        alt.Y(alt.repeat("row"), type = 'quantitative', scale = alt.Scale (nice = True)),
        color = 'target:N'
    ).properties(
        width=150,
        height=150
    ).repeat(
        row = features,
        column = features
    )#.interactive()
    
    return chart

In [14]:
chart_scatter_wine = create_scatter_matrix (data_wine)
chart_scatter_wine

alt.RepeatChart(...)

### Exercise:
(**EASY**) Implement linking and brushing for the chart above.
* Linking - *showing how a point, or set of points, behaves in each of the plots.*
* Brushing - *the points to be highlighted are interactively selected by a mouse and the scatterplot matrix is dynamically updated.*

### Exercise:
(**HARD**) Show only the lower triangle of the image above.


# Homework 8

Use everything you learned in this notebook to explore and analyze `ori.dat` data set. Use *pandas'* ***read_csv*** function, with adequate parameters, to import the data.

Export your resulting data visualizations as a multi-HTML file.